// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: kwseeker.top/kwseeker/go-template/basic/net/socks/v2ray/common/protocol/packetaddr.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PacketAddrType int32

const (
	PacketAddrType_None   PacketAddrType = 0
	PacketAddrType_Packet PacketAddrType = 1
)

// Enum value maps for PacketAddrType.
var (
	PacketAddrType_name = map[int32]string{
		0: "None",
		1: "Packet",
	}
	PacketAddrType_value = map[string]int32{
		"None":   0,
		"Packet": 1,
	}
)

func (x PacketAddrType) Enum() *PacketAddrType {
	p := new(PacketAddrType)
	*p = x
	return p
}

func (x PacketAddrType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketAddrType) Descriptor() protoreflect.EnumDescriptor {
	return file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_enumTypes[0].Descriptor()
}

func (PacketAddrType) Type() protoreflect.EnumType {
	return &file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_enumTypes[0]
}

func (x PacketAddrType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketAddrType.Descriptor instead.
func (PacketAddrType) EnumDescriptor() ([]byte, []int) {
	return file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescGZIP(), []int{0}
}

var File_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto protoreflect.FileDescriptor

var file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDesc = []byte{
	0x0a, 0x58, 0x6b, 0x77, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x2f, 0x6b,
	0x77, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x2f, 0x62, 0x61, 0x73, 0x69, 0x63, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x73, 0x6f,
	0x63, 0x6b, 0x73, 0x2f, 0x76, 0x32, 0x72, 0x61, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x61, 0x64, 0x64, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x62, 0x61, 0x73, 0x69,
	0x63, 0x2e, 0x6e, 0x65, 0x74, 0x2e, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x2e, 0x76, 0x32, 0x72, 0x61,
	0x79, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2a, 0x26, 0x0a, 0x0e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0a, 0x0a,
	0x06, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x10, 0x01, 0x42, 0x49, 0x5a, 0x47, 0x6b, 0x77, 0x73,
	0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x2f, 0x6b, 0x77, 0x73, 0x65, 0x65, 0x6b,
	0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x62,
	0x61, 0x73, 0x69, 0x63, 0x2f, 0x6e, 0x65, 0x74, 0x2f, 0x73, 0x6f, 0x63, 0x6b, 0x73, 0x2f, 0x76,
	0x32, 0x72, 0x61, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescOnce sync.Once
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescData = file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDesc
)

func file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescGZIP() []byte {
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescOnce.Do(func() {
		file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescData = protoimpl.X.CompressGZIP(file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescData)
	})
	return file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDescData
}

var file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_goTypes = []interface{}{
	(PacketAddrType)(0), // 0: basic.net.socks.v2ray.common.protocol.PacketAddrType
}
var file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_init()
}
func file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_init() {
	if File_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_goTypes,
		DependencyIndexes: file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_depIdxs,
		EnumInfos:         file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_enumTypes,
	}.Build()
	File_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto = out.File
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_rawDesc = nil
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_goTypes = nil
	file_kwseeker_top_kwseeker_go_template_basic_net_socks_v2ray_common_protocol_packetaddr_proto_depIdxs = nil
}
