// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: kwseeker.top/kwseeker/go-template/configuration/jsonpb/config.proto

package jsonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContactType int32

const (
	ContactType_Phone ContactType = 0
	ContactType_Email ContactType = 1
)

// Enum value maps for ContactType.
var (
	ContactType_name = map[int32]string{
		0: "Phone",
		1: "Email",
	}
	ContactType_value = map[string]int32{
		"Phone": 0,
		"Email": 1,
	}
)

func (x ContactType) Enum() *ContactType {
	p := new(ContactType)
	*p = x
	return p
}

func (x ContactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContactType) Descriptor() protoreflect.EnumDescriptor {
	return file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_enumTypes[0].Descriptor()
}

func (ContactType) Type() protoreflect.EnumType {
	return &file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_enumTypes[0]
}

func (x ContactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContactType.Descriptor instead.
func (ContactType) EnumDescriptor() ([]byte, []int) {
	return file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescGZIP(), []int{0}
}

type Contact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Addr string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
}

func (x *Contact) Reset() {
	*x = Contact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescGZIP(), []int{0}
}

func (x *Contact) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Contact) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type MyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age      int32      `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Contacts []*Contact `protobuf:"bytes,3,rep,name=contacts,proto3" json:"contacts,omitempty"`
}

func (x *MyMessage) Reset() {
	*x = MyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyMessage) ProtoMessage() {}

func (x *MyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyMessage.ProtoReflect.Descriptor instead.
func (*MyMessage) Descriptor() ([]byte, []int) {
	return file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescGZIP(), []int{1}
}

func (x *MyMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyMessage) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *MyMessage) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

var File_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto protoreflect.FileDescriptor

var file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDesc = []byte{
	0x0a, 0x43, 0x6b, 0x77, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x74, 0x6f, 0x70, 0x2f, 0x6b,
	0x77, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c,
	0x61, 0x74, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x22, 0x31, 0x0a, 0x07, 0x43,
	0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64,
	0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x22, 0x6c,
	0x0a, 0x09, 0x4d, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x61, 0x67,
	0x65, 0x12, 0x39, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x73, 0x2a, 0x23, 0x0a, 0x0b,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x50,
	0x68, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x10,
	0x01, 0x42, 0x38, 0x5a, 0x36, 0x6b, 0x77, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2e, 0x74, 0x6f,
	0x70, 0x2f, 0x6b, 0x77, 0x73, 0x65, 0x65, 0x6b, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x2d, 0x74, 0x65,
	0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x6a, 0x73, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescOnce sync.Once
	file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescData = file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDesc
)

func file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescGZIP() []byte {
	file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescOnce.Do(func() {
		file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescData)
	})
	return file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDescData
}

var file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_goTypes = []interface{}{
	(ContactType)(0),  // 0: configuration.jsonpb.ContactType
	(*Contact)(nil),   // 1: configuration.jsonpb.Contact
	(*MyMessage)(nil), // 2: configuration.jsonpb.MyMessage
}
var file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_depIdxs = []int32{
	1, // 0: configuration.jsonpb.MyMessage.contacts:type_name -> configuration.jsonpb.Contact
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_init() }
func file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_init() {
	if File_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_goTypes,
		DependencyIndexes: file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_depIdxs,
		EnumInfos:         file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_enumTypes,
		MessageInfos:      file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_msgTypes,
	}.Build()
	File_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto = out.File
	file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_rawDesc = nil
	file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_goTypes = nil
	file_kwseeker_top_kwseeker_go_template_configuration_jsonpb_config_proto_depIdxs = nil
}
